In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('dataset.csv')
data.head(10)

,sat_neo6m,lon_neo6m,lat_neo6m,hdop_neo6m,sat_sim28m,lon_sim28m,lat_sim28m,hdop_sim28m,distance,status
0,4,104.764122,-2.913845,1.65,5,104.764137,-2.913897,1.52,6.02,0
1,4,104.764122,-2.913845,1.65,5,104.764137,-2.913897,1.52,6.02,0
2,4,104.764130,-2.913853,1.65,5,104.764137,-2.913897,1.52,4.87,1
3,4,104.764145,-2.913863,1.65,5,104.764137,-2.913897,1.52,3.83,1
4,4,104.764137,-2.913864,1.61,5,104.764137,-2.913897,1.52,3.66,1
5,4,104.764145,-2.913864,1.61,5,104.764137,-2.913897,1.52,3.73,1
6,4,104.764145,-2.913876,1.61,5,104.764137,-2.913903,1.52,3.17,1
7,4,104.764153,-2.913879,1.61,5,104.764145,-2.913913,1.52,3.89,1
8,4,104.764153,-2.913882,1.61,5,104.764145,-2.913918,1.52,4.14,1
9,4,104.764153,-2.913883,1.61,5,104.764153,-2.913927,1.52,4.88,1

In [3]:
pd.isna(data)

,sat_neo6m,lon_neo6m,lat_neo6m,hdop_neo6m,sat_sim28m,lon_sim28m,lat_sim28m,hdop_sim28m,distance,status
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
399,False,False,False,False,False,False,False,False,False,False
400,False,False,False,False,False,False,False,False,False,False
401,False,False,False,False,False,False,False,False,False,False
402,False,False,False,False,False,False,False,False,False,False
403,False,False,False,False,False,False,False,False,False,False

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404 entries, 0 to 403
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sat_neo6m    404 non-null    int64
 1   lon_neo6m    404 non-null    float64
 2   lat_neo6m    404 non-null    float64
 3   hdop_neo6m   404 non-null    float64
 4   sat_sim28m   404 non-null    int64
 5   lon_sim28m   404 non-null    float64
 6   lat_sim28m   404 non-null    float64
 7   hdop_sim28m  404 non-null    float64
 8   distance     404 non-null    float64
 9   status       404 non-null    int64
dtypes: float64(7), int64(3)
memory usage: 31.7 KB

In [5]:
inputs = data.drop(columns='status')
inputs.head(10)

,sat_neo6m,lon_neo6m,lat_neo6m,hdop_neo6m,sat_sim28m,lon_sim28m,lat_sim28m,hdop_sim28m,distance
0,4,104.764122,-2.913845,1.65,5,104.764137,-2.913897,1.52,6.02
1,4,104.764122,-2.913845,1.65,5,104.764137,-2.913897,1.52,6.02
2,4,104.764130,-2.913853,1.65,5,104.764137,-2.913897,1.52,4.87
3,4,104.764145,-2.913863,1.65,5,104.764137,-2.913897,1.52,3.83
4,4,104.764137,-2.913864,1.61,5,104.764137,-2.913897,1.52,3.66
5,4,104.764145,-2.913864,1.61,5,104.764137,-2.913897,1.52,3.73
6,4,104.764145,-2.913876,1.61,5,104.764137,-2.913903,1.52,3.17
7,4,104.764153,-2.913879,1.61,5,104.764145,-2.913913,1.52,3.89
8,4,104.764153,-2.913882,1.61,5,104.764145,-2.913918,1.52,4.14
9,4,104.764153,-2.913883,1.61,5,104.764153,-2.913927,1.52,4.88

In [6]:
output = data['status']
output.head(10)

0    0
1    0
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: status, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier

In [8]:
xtrain, xtest, ytrain, ytest = train_test_split(inputs, output, test_size=0.3)
tree_data = DecisionTreeClassifier()
tree_data.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [9]:
score = tree_data.score(xtest,ytest)
score

1.0

In [19]:
prediction = tree_data.predict([[5,104.764160,-2.913836,1.78,8,104.764183,-2.913868,0.94,4.43,]])
prediction

c:\Users\MICROPANG\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [11]:
from sklearn.tree import export_graphviz
export_graphviz(tree_data, out_file="tree_gps.dot", class_names=["1", "0"], feature_names=inputs.columns, impurity=True, filled=True)

In [12]:
import graphviz
with open("tree_gps.dot") as fig:
    dot_graph = fig.read()
graphviz.Source(dot_graph)